### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by piotr-gawron** [chembl/chembl_webservices_2#184]
Today the request that I was using for some time started returning 500:
```
curl https://www.ebi.ac.uk/chembl/api/data/target?limit=1000&target_components__accession=O15217
```

Error:
```
<error_message>argument of AND must be type boolean, not type smallint LINE 1: ...d" = "component_sequences"."component_id") WHERE ("target_di... ^ </error_message>
<traceback>Traceback (most recent call last): File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) psycopg2.errors.DatatypeMismatch: argument of AND must be type boolean, not type smallint LINE 1: ...d" = "component_sequences"."component_id") WHERE ("target_di... ^ The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/chembl_ws_py3/src/chembl_webservices/core/resource.py", line 440, in handle count = sorted_objects.count() if not isinstance(sorted_objects, list) else len(sorted_objects) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/models/query.py", line 412, in count return self.query.get_count(using=self.db) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/models/sql/query.py", line 519, in get_count number = obj.get_aggregation(using, ['__count'])['__count'] File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/models/sql/query.py", line 504, in get_aggregation result = compiler.execute_sql(SINGLE) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql cursor.execute(sql, params) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute return super().execute(sql, params) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/opt/conda/envs/chembl-webservices-py3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) django.db.utils.ProgrammingError: argument of AND must be type boolean, not type smallint LINE 1: ...d" = "component_sequences"."component_id") WHERE ("target_di... ^ </traceback>
```

When I try to access documentation there is also 500:
https://www.ebi.ac.uk/chembl/api/data/docs

**Comment by alrichardbollans** [comment]
Getting similar errors today. Guess the server is down

**Comment by alrichardbollans** [comment]
It's back up
